### ISSUE TITLE
windows debug build (when built on linux) uses wrong path seperators

### ISSUE THREAD

**Issue by benjamin-sieffert** [evolutics/iftree#11]
When building on Linux, but for Windows, via mingw and `--target x86_64-pc-windows-gnu`.
In release mode, everything works perfectly.
In debug mode, compilation succeeds, but the produced executable, when moved to windows, will use paths with `/` as seperator rather than `\` and hence fail to find the resources to load.
(I am not using stock debug mode, rather a special profile I created, see #10. But should not make a difference.)

I can fix that by specifying Windows-style paths in the iftree macro invocations, e.g.
`#[iftree::include_file_tree("res\\myres\\*jpg")]`
But obviously then I break release-builds, because those are trying to use Linux-style paths to embed the files from current system.

Regards

**Comment by evolutics** [comment]
When using a `get_*` [standard field](https://github.com/evolutics/iftree?tab=readme-ov-file#standard-fields), then debug binaries use absolute paths from the system where compiled, meaning they aren't portable. This mode is meant for quick iteration while developing. For a portable binary, best use a `contents_*` standard field if that makes sense.

For alternatives using relative paths, see #10.

**Comment by benjamin-sieffert** [comment]
>they aren't portable

OK, it was not clear to me that this is by design. Unfortunate! Thanks for the clarification.
